### ISSUE TITLE
discussion: Food for thought

### ISSUE THREAD

**Issue by DaddyWarbucks** [RubyRubenstahl/feathers-rc#20]
I posted in the Feathers slack channel about having done something "similar" and thought I would share my code. I think it is probably _too_ specific to my own app structure to be useful...but I thought I would share anyway.
Some notes
- I use immutable.js `Record`s which I kind of extend to be vary backbone.js like. So `this.props.record.find()` basically maps to a service's find method.
- All of my records (basically AKA services) have after hooks on them that turn the results intto their respective immutable record and also sets them in state.
- I have some server side hooks to handle `$page`.

So, like I said, this is quite a bit different and very specific to my own application structure and may not be helpful at all.

```
import React, { Component } from 'react';
import { Map } from 'immutable';

export default class WithRecords extends Component {
  constructor(props) {
    super(props);
    this.pagination = 50;
    const { store, defaultQuery, defaultPage } = this.props;
    // Initially return what we know from state, unless a deafaultQuery
    // is given in which return and empty List until query is executed.
    const initialResources = defaultQuery
      ? Map()
      : store.slice(
          defaultPage * this.pagination - this.pagination,
          Math.min(store.size, this.pagination)
        );
    const initialPageIds = initialResources
      .toList()
      .map(resource => resource._id);
    this.state = {
      initialized: false,
      currentPage: defaultPage,
      currentPageIds: initialPageIds,
      total: initialPageIds.size,
      resources: initialResources
    };
  }

  componentDidMount = () => {
    this.goToPage();
  };

  goToPage = async (
    pageNumber = this.props.defaultPage,
    _query = this.props.defaultQuery
  ) => {
    const query = { ..._query, $page: pageNumber };
    try {
      const { data: resources, total } = await this.props.record.find({
        query
      });
      const currentPageIds = resources.toList().map(resource => resource._id);
      this.setState({
        initialized: true,
        currentPage: pageNumber,
        currentPageIds,
        total,
        resources
      });
    } catch (err) {
      console.log('Error in goToPage:', err);
    }
  };

  render() {
    return (
      <React.Fragment>
        {this.props.render({
          ...this.state,
          goToPage: this.goToPage
        })}
      </React.Fragment>
    );
  }
}

WithRecords.defaultProps = {
  defaultPage: 1
};
```

**Comment by RubyRubenstahl** [comment]
It's definitely helpful to see someone else's approach. 

I've actually been thinking about using immutable in the background to cache the query results at the provider level (issue #7) so that the cache can be shared amongst all components. 

I'm trying to keep everything client-side only, with the goal of not having to do anything special on the server to allow the components to interact. My ideal goal is to be able to create an app with feathers CLI, add a service, then import feathers-rc on the frontend and start writing your business logic.
